import pytest
import pandas as pd
from backend.backtest.scenario_scorer import ScenarioScorer

@pytest.fixture
def mock_signals_df():
    # 3 tickers, generated by 3 different strategies
    return pd.DataFrame({
        'date': [pd.Timestamp('2024-01-01')] * 5,
        'symbol_id': [1, 1, 2, 3, 3],
        'ticker': ['AAPL', 'AAPL', 'MSFT', 'GOOG', 'GOOG'],
        'strategy_name': ['A', 'B', 'A', 'B', 'C'],
        'rs21_rank': [80.0, 80.0, 90.0, 75.0, 75.0]
    })

def test_scenario_scorer_counts_votes(mock_signals_df):
    scorer = ScenarioScorer(target_group_prefix=None)
    # AAPL has 2 hits, MSFT 1 hit, GOOG 2 hits
    scored_df = scorer.score_signals(mock_signals_df, date=pd.Timestamp('2024-01-01'))
    
    assert len(scored_df) == 3
    
    aapl_score = scored_df[scored_df['ticker'] == 'AAPL']['score'].values[0]
    msft_score = scored_df[scored_df['ticker'] == 'MSFT']['score'].values[0]
    goog_score = scored_df[scored_df['ticker'] == 'GOOG']['score'].values[0]
    
    assert aapl_score == 2
    assert msft_score == 1
    assert goog_score == 2

def test_scenario_scorer_tie_break(mock_signals_df):
    scorer = ScenarioScorer(target_group_prefix=None)
    scored_df = scorer.score_signals(mock_signals_df, date=pd.Timestamp('2024-01-01'))
    
    # AAPL and GOOG both have score 2. 
    # AAPL rs21_rank is 80, GOOG is 75. AAPL should be ranked higher.
    top_ticker = scored_df.iloc[0]['ticker']
    second_ticker = scored_df.iloc[1]['ticker']
    
    assert top_ticker == 'AAPL'
    assert second_ticker == 'GOOG'

def test_scenario_scorer_filters_by_group():
    # Signals with strategies from different groups
    df = pd.DataFrame({
        'date': [pd.Timestamp('2024-01-01')] * 3,
        'symbol_id': [1, 1, 1],
        'ticker': ['AAPL', 'AAPL', 'AAPL'],
        'strategy_name': ['Rise - Check 1', 'Rise - Check 2', 'Other Strategy'],
        'rs21_rank': [80.0, 80.0, 80.0]
    })
    
    scorer = ScenarioScorer(target_group_prefix='Rise - Check')
    scored_df = scorer.score_signals(df, date=pd.Timestamp('2024-01-01'))
    
    # Should only count the 2 strategies matching the prefix
    assert scored_df.iloc[0]['score'] == 2

def test_scenario_scorer_empty_data():
    scorer = ScenarioScorer()
    empty_df = pd.DataFrame(columns=['date', 'symbol_id', 'ticker', 'strategy_name', 'rs21_rank'])
    scored_df = scorer.score_signals(empty_df, date=pd.Timestamp('2024-01-01'))
    
    assert len(scored_df) == 0
